spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trading_db
    username: trading_user
    password: trading_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect