global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # - job_name: 'kafka'
  #   static_configs:
  #     - targets: ['kafka:29092']

  - job_name: 'trading-services'
    static_configs:
      - targets: 
        - 'market-data-service:8081'
        - 'order-management-service:8082'
        - 'risk-management-service:8083'
        - 'user-service:8084'

  - job_name: 'databases'
    static_configs:
      - targets: 
        - 'postgres:5432'
        - 'redis:6379'
        - 'influxdb:8086'